# Generated by Django 6.0.1 on 2026-01-12 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('EN_MANTENCION', 'En Mantención')], default='DISPONIBLE', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='herramientas/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.categoria')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodega.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('bodeguero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devuelto', models.BooleanField(default=False)),
                ('estado_devolucion', models.CharField(blank=True, max_length=20, null=True)),
                ('observacion_falla', models.TextField(blank=True, null=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.herramienta')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.prestamo')),
            ],
        ),
    ]
