# Generated by Django 6.0.1 on 2026-01-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprestamo',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/'),
        ),
    ]
