# Generated by Django 6.0.1 on 2026-01-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_detalleprestamo_foto_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprestamo',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
