# Generated by Django 6.0.1 on 2026-01-12 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_detalleprestamo_fecha_devolucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='imagen',
        ),
        migrations.AddField(
            model_name='herramienta',
            name='imagen_qr',
            field=models.ImageField(blank=True, null=True, upload_to='codigos_qr/'),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='codigo_qr',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='estado',
            field=models.CharField(default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bodega.ubicacion'),
            preserve_default=False,
        ),
    ]
