# Generated by Django 6.0.1 on 2026-01-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_remove_herramienta_imagen_herramienta_imagen_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activa en Sistema'),
        ),
    ]
