# Generated by Django 6.0.1 on 2026-01-15 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_herramienta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='detalleprestamo',
            name='herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodega.herramienta'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodega.trabajador'),
        ),
    ]
