# Generated by Django 6.0.1 on 2026-01-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0006_categoria_activo_ubicacion_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('EN_MANTENCION', 'En Mantención'), ('DE_BAJA', 'De Baja / Eliminada')], default='DISPONIBLE', max_length=20),
        ),
    ]
