# Generated by Django 6.0.1 on 2026-01-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0007_alter_herramienta_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
    ]
