# Generated by Django 6.0.1 on 2026-01-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0008_alter_trabajador_options_alter_ubicacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprestamo',
            name='estado_devolucion',
            field=models.CharField(blank=True, choices=[('DISPONIBLE', 'Bueno / Operativo'), ('EN_MANTENCION', 'Dañado / Falla')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('EN_MANTENCION', 'En Mantención'), ('DE_BAJA', 'De Baja Administrativa'), ('BAJA_POR_DANO', 'Baja por Daño'), ('BAJA_POR_PERDIDA', 'Baja por Pérdida')], default='DISPONIBLE', max_length=20),
        ),
    ]
