# Generated by Django 6.0.1 on 2026-01-18 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0009_alter_detalleprestamo_estado_devolucion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('BAJA', 'Dar de Baja'), ('REACTIVACION', 'Reactivación / Alta')], max_length=20)),
                ('motivo', models.CharField(max_length=100)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.herramienta')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
